### ISSUE TITLE
chore: Remodel ToDo and Deleted Document list

### ISSUE THREAD

**Issue by SaiFi0102** [ParaLogicTech/erpnext#38]
- [x] Add (non-mandatory) title field in ToDo so that title on the Form View is set from the new title field OR if title not set then from the description. See how title is set in purchase_receipt.py and purchase_invoice.py `set_title()` for reference. Also see that there is an option to set from which field the Form View will show title and change that from description to your new title field

- [x] Add that new title field in list view standard filters (there's a checkbox in DocType's field row)

- [x] Note that widths of Form Views and List View all pages do not use the whole width properly (as seen in the image not being able to show the complete description). Also see that on smaller resolution screens the page layout gets messed up in the the part where the "Menu" and "Save" button is

![image](https://user-images.githubusercontent.com/328330/95558933-6db1aa00-0a30-11eb-8bad-4aa4f28ce0eb.png)

- [x] Add Deleted DocType field in Standard Filters in Deleted Document DocType
