### ISSUE TITLE
Techno Version 12 Migration ToDo List

### ISSUE THREAD

**Issue by beingeek** [ParaLogicTech/erpnext#9]
### Configuration

- [x] Sales Invoice incorrect series for Tax Invoice

### DocType or Customization Modification
- [x] Label for Tax ID showing as STRN rather than NTN
- [x] Item Price DocType force currency symbol for price
- [x] Payment Entry: Hide "Get Outstanding Invoices" button if submitted
- [x] Add Weighted Distribution in Purchase Taxes and Charges
- [x] Hide Item Group from Stock Entry Detail and convert to Link fieldtype

### Code Bugs
- [x] Sales Invoice print format
- [x] Purchase Receipt billed_valuation_tax_amount accounting entry fix
- [x] Delivery Note -> Sales Invoice: filter out 0 qty rows
- [x] Accounts Receivable print format remove empty title: "Cost Center: " and project..
- [x] Payment Entry "Get Outstanding Invoices" with filters not working
- [x] Sales Details report ungrouped and merged items error
